import { readFile, mkdir, writeFile } from "node:fs/promises";

// One model source of truth: never hand-maintain two independent sets of models.
const canonical = await readFile(new URL("../prisma/schema.prisma", import.meta.url), "utf8");
const generated = canonical
  .replace('provider = "prisma-client-js"', 'provider = "prisma-client-js"\n  output = "../../node_modules/@prisma/postgres-client"')
  .replace('provider = "sqlite"', 'provider = "postgresql"')
  .replace('url      = env("DATABASE_URL")', 'url      = env("DATABASE_URL")\n  directUrl = env("DATABASE_URL_UNPOOLED")')
  .replace('// We use SQLite for local dev. This can be easily swapped to postgres for production.', '// Generated by tooling/postgres-schema.mjs; edit canonical models instead.')
  .replace(/[ \t]+$/gm, "");
const target = new URL("../prisma/postgres/schema.prisma", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(target, "utf8") !== generated) throw new Error("Hosted schema is out of date; run npm run db:generate");
} else {
  await mkdir(new URL("../prisma/postgres/", import.meta.url), { recursive: true });
  await writeFile(target, generated);
}
